### ISSUE TITLE
Criar VM

### ISSUE THREAD

**Issue by Jopacheco** [MicrosoftDocs/azure-docs.pt-pt#41]
Em Criar VM-Cl do Azure, o comando az vm create está com "z vm create"

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 074568ee-1fc9-3d9a-1c10-96ada221c0aa
* Version Independent ID: 9e5ebd88-534b-3d7e-f145-03797a56330f
* Content: [Tutorial - Criar e gerir VMs do Linux com a CLI do Azure](https://docs.microsoft.com/pt-pt/azure/virtual-machines/linux/tutorial-manage-vm#management-tasks)
* Content Source: [articles/virtual-machines/linux/tutorial-manage-vm.md](https://github.com/MicrosoftDocs/azure-docs.pt-pt/blob/live/articles/virtual-machines/linux/tutorial-manage-vm.md)
* Service: **virtual-machines-linux**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by CeciAc** [comment]
Hello, @Jopacheco
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/pt-pt/azure/virtual-machines/linux/tutorial-manage-vm#management-tasks.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
