### ISSUE TITLE
Correção para português

### ISSUE THREAD

**Issue by rogerql** [MicrosoftDocs/azure-docs.pt-pt#444]
Tomadas Web -&gt; Websockets

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: bcf2a86a-1de0-2786-db87-58279ceffb22
* Version Independent ID: 7e43624f-a87d-1c4d-94e6-e38c1d42686f
* Content: [Compreenda o suporte do Hub MQTT do Azure IoT Microsoft Docs](https://docs.microsoft.com/pt-pt/azure/iot-hub/iot-hub-mqtt-support#feedback)
* Content Source: [articles/iot-hub/iot-hub-mqtt-support.md](https://github.com/MicrosoftDocs/azure-docs.pt-pt/blob/master/articles/iot-hub/iot-hub-mqtt-support.md)
* Service: **iot-hub**
* GitHub Login: @robinsh
* Microsoft Alias: **robinsh**

**Comment by srvbpigh** [comment]
Hello, @rogerql
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá @rogerql

Obrigado pelo seu contributo.

Os contributos sobre problemas de tradução de conteúdo traduzido automaticamente não são atualmente aceites.

Valorizamos o seu feedback e sugestões sobre conteúdo traduzido por humanos, utilizado para preparar os motores de tradução automática, pelo que, com o tempo, as suas contribuições vão melhorar a qualidade de todas as traduções.

Os tópicos traduzidos por humanos podem ser distinguidos dos tópicos traduzidos automaticamente pelo valor de metadados ms.translationtype "HT" (versus "MT" para as traduções automáticas) no cabeçalho de cada ficheiro de conteúdo.

Muito obrigado pelo seu apoio.

Equipa de Experiência Global do Microsoft DOCS
