### ISSUE TITLE
issues with translation.

### ISSUE THREAD

**Issue by jovieir** [MicrosoftDocs/azure-docs.pt-pt#445]
Hi team,

Just to point out two issues with PT translation (top to bottom):

Lago cascade (Cascade Lake) - this shouldn't be translated.

Table - Sizes M64ls, M64m, M128m are listed with a lower font size.

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 214d459e-48c9-9a8f-65f0-0febb5c5b215
* Version Independent ID: e0ad25f2-56c2-db86-1919-52dcfea33e4c
* Content: [Série M - Máquinas Virtuais Azure](https://docs.microsoft.com/pt-pt/azure/virtual-machines/m-series#feedback)
* Content Source: [articles/virtual-machines/m-series.md](https://github.com/MicrosoftDocs/azure-docs.pt-pt/blob/master/articles/virtual-machines/m-series.md)
* Service: **virtual-machines**
* GitHub Login: @ayshakeen
* Microsoft Alias: **jushiman**

**Comment by srvbpigh** [comment]
Hello, @jovieir
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @jovieir 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
