### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by jovieir** [MicrosoftDocs/azure-docs.pt-pt#446]
Hi team,

The PT translation lists "Rio Lsv2" under "Com otimização de armazenamento". 

"Rio" shouldn't be there (it stands for river) :)

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 39662d32-ec4d-7826-37b9-6bc76b70fe2b
* Version Independent ID: c83e4c16-0add-2271-94be-572a360350d2
* Content: [Tamanhos De Linux VM em Azure](https://docs.microsoft.com/pt-pt/azure/virtual-machines/linux/sizes)
* Content Source: [articles/virtual-machines/linux/sizes.md](https://github.com/MicrosoftDocs/azure-docs.pt-pt/blob/master/articles/virtual-machines/linux/sizes.md)
* Service: **virtual-machines**
* Sub-service: **sizes**
* GitHub Login: @ju-shim
* Microsoft Alias: **jushiman**

**Comment by srvbpigh** [comment]
Hello, @jovieir
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @jovieir 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team

**Comment by jovieir** [comment]
Hi Cecilia,

Thanks for the feedback.

I've been running across plenty of PT MT translated articles with a variety of mistranslations.
What would be the correct procedure to help drive up the accuracy of the machine learning algorithm?

Thanks!

João l

Get Outlook for Android<https://aka.ms/ghei36>
